sudo: required
services:
  - docker
  
before_install:
  - docker build -t ehazak/docker-react -f Dockerfile.dev .

script:
  - docker run ehazak/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region:  "us-west-1"
  app: "udemy-docker"
  env: "UdemyDocker-env"
  bucket_name: "elasticbeanstalk-us-west-1-177532915676"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
